### ISSUE TITLE
Missing parentheses for boolean operations

### ISSUE THREAD

**Issue by miniBill** [mdgriffith/elm-codegen#25]
This code:
```elm
(Elm.Op.and (Elm.bool False)
    (Elm.Op.or (Elm.bool True)
        (Elm.bool True)
    )
)
```

Produces

```elm
False && True || True
```

instead of

```elm
False && (True || True)
```

Which drastically changes the meaning.

**Comment by mdgriffith** [comment]
Good catch!

Now each term in an infix op will potentially get parens if appropriate (as determined by `Compiler.parens`)
