### ISSUE TITLE
Generating case statements to match on ints

### ISSUE THREAD

**Issue by r-k-b** [mdgriffith/elm-codegen#99]
I'm upgrading to elm-codegen 5.0.0, but stuck on trying to generate a case expression like this:

```elm
case int of
    0 ->
        True
    1 ->
        False
    _ ->
        True
```

It seems as though it's not possible to pattern match on `Int` values.

Thanks for your help, elm-codegen is great! :heart:

**Comment by r-k-b** [comment]
terribly sorry to be a bother @mdgriffith, but could I trouble you for a 5.0.2 version that includes the fix? thanks so much! :pray: 

![image](https://github.com/user-attachments/assets/acc62d7b-c9e6-4f18-8d4e-b48b58e59380)

**Comment by mdgriffith** [comment]
Oh whoops I didn't see that PR was attached to this issue!  Thank you for the ping.

Yes, 5.1.0 is now released!  Sorry for the delay 🙏
